# Generated by Django 4.2.30 on 2026-05-25 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ['department', 'degree_level', 'degree_type', 'name', 'option_name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='department',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='degree_level',
            field=models.CharField(choices=[('UNDERGRADUATE', 'Undergraduate'), ('MASTERS', 'Masters'), ('DOCTORAL', 'Doctoral')], default='UNDERGRADUATE', max_length=20),
        ),
        migrations.AddField(
            model_name='programme',
            name='duration_semesters',
            field=models.IntegerField(default=8, help_text='Total semesters for the programme'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_semester',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='user',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='expected_graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='degree_type',
            field=models.CharField(choices=[('BENG', 'Bachelor of Engineering (BEng)'), ('TOPUP_BENG', 'Top-up Bachelor of Engineering'), ('MENG', 'Master of Engineering (MEng)'), ('TOPUP_MENG', 'Top-up Master of Engineering'), ('MSC_ENG', 'Master of Science in Engineering (MSc Eng)'), ('TOPUP_MSC', 'Top-up Master of Science'), ('PHD', 'Doctor of Philosophy (PhD)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='programme',
            name='option_name',
            field=models.CharField(blank=True, help_text='Specialization/Option', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterUniqueTogether(
            name='programme',
            unique_together={('department', 'degree_type', 'name', 'option_name')},
        ),
        migrations.RemoveField(
            model_name='programme',
            name='code',
        ),
    ]
