AUTH_METHOD = 'fasiva_2fa'

# FaSIVA verification thresholds. Identity is decided primarily by structure
# and local texture; lighting-sensitive histogram/edge scores are audit signals.
MATCH_CONFIDENCE_THRESHOLD = 68
VECTOR_SCORE_THRESHOLD = 0.60
LBP_SCORE_THRESHOLD = 0.88
SUPPORTING_SCORE_THRESHOLD = 0.40
HISTOGRAM_SCORE_THRESHOLD = 0.00
EDGE_SCORE_THRESHOLD = 0.00

MAX_FAILED_ATTEMPTS = 5
MIN_LIVENESS_CONFIDENCE = 0.45
MIN_FACE_SHARPNESS = 20.0
MIN_FACE_BRIGHTNESS = 35.0
MAX_FACE_BRIGHTNESS = 220.0
BLINK_EVIDENCE_REQUIRED = False
