# Generated by Django 5.2.14 on 2026-05-18 04:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('credits', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('status_type', models.CharField(choices=[('Compulsory', 'Compulsory'), ('Required', 'Required'), ('Elective', 'Elective')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('ca_weight', models.IntegerField(default=30)),
                ('exam_weight', models.IntegerField(default=70)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CourseProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('semester', models.IntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester')])),
                ('is_core', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.course')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.programme')),
            ],
            options={
                'unique_together': {('programme', 'course', 'year', 'semester')},
            },
        ),
    ]
