# Generated by Django 5.2.14 on 2026-05-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_letter', models.CharField(max_length=2, unique=True)),
                ('min_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=3)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-grade_point'],
            },
        ),
        migrations.CreateModel(
            name='UserMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exam_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semester', models.IntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester')])),
                ('academic_year', models.CharField(max_length=9)),
                ('attempt_number', models.IntegerField(default=1)),
                ('exclude_from_cgpa', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
